services:

  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_DEBUG=$DJANGO_DEBUG
      - DJANGO_SUPERUSER_USERNAME=$DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL
    # volumes:
    #   - ./run.sh:/app/run.sh
    ports:
      - 8000:8000
    command: bash run.sh

